//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSCampain
    {
        public int Idpk { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string SMSText { get; set; }
        public Nullable<int> CharacterCount { get; set; }
        public Nullable<int> Success { get; set; }
        public Nullable<int> Failure { get; set; }
        public Nullable<int> SMSCountBefore { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string ContactNo { get; set; }
    }
}
