//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Idpk { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
