//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int Idpk { get; set; }
        public string PackageName { get; set; }
        public System.Guid UID { get; set; }
        public int SMSnum { get; set; }
        public int Duration { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
