//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Idpk { get; set; }
        public string Name { get; set; }
        public string Masking { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
