//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSPortal
{
    using System;
    
    public partial class GetSchedleList_Result
    {
        public int Idpk { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public string TextSms { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
